OpenLiberty/liberty-tools-eclipse

liberty/src/liberty/tools/utils/Project.java
Signed-off-by: Andrew J. Mauer <ajmauer@gmail.com>
=> get project path in a os neutral manner

.project, liberty/plugin.xml, liberty/src/liberty/tools/DevModeOperations.java, liberty/src/liberty/tools/LibertyNature.java, liberty/src/liberty/tools/ui/DevModeView.java, liberty/src/liberty/tools/utils/Project.java
Various updates:
- Introduces a Liberty nature/type.
- Issues a warning message if test report not found.
- Adds basic liberty project filtering.
- Fixes Gradle command.
- Others.
=> Various updates

liberty/plugin.xml, liberty/src/liberty/tools/DevModeOperations.java, liberty/src/liberty/tools/handlers/DashboardHandler.java, liberty/src/liberty/tools/ui/DashboardView.java, liberty/src/liberty/tools/utils/Project.java
Adds a refresh icon to dashboard and project list refresh capability behind it.
=> Allow dashboard project list to be refreshed.

liberty/src/liberty/tools/DevModeOperations.java
=> Launch with /c, mvn.cmd on Windows

bundles/liberty/META-INF/MANIFEST.MF
=> Change from Require-Bundle to Import-Package

tests/src/liberty/tools/test/it/LibertyPluginSWTBotMavenTest.java
=> Add terminal.close() and increase retry for test

.github/workflows/run-regression-tests.yml, tests/resources/ci/scripts/exec.sh, tests/resources/ci/scripts/setup.sh, tests/src/liberty/tools/test/it/LibertyPluginSWTBotMavenTest.java, tests/src/liberty/tools/test/it/utils/SWTPluginOperations.java
This PR adds support for building and testing the plugin (pre-integration validation) on Linux, Mac, and Windows platforms.
=> GHA Multi-OS test support

bundles/liberty-mpls/META-INF/MANIFEST.MF, bundles/liberty-mpls/plugin.xml, releng/target-platform/target-platform.target, tests/resources/applications/maven/liberty-maven-test-app/pom.xml
=> Remove MP Java content type; Add o.e.lsp4e.jdt as dependency

bundles/liberty-mpls/META-INF/MANIFEST.MF, releng/target-platform/target-platform.target, tests/resources/ci/scripts/setup.sh
=> Consolidate dependency download locations and update versions

bundles/liberty/src/liberty/tools/utils/Dialog.java
Solves a flagged sec scan issue.
=> Update error dialog with exception

bundles/liberty/src/liberty/tools/DevModeOperations.java
fixes #86 
Signed-off-by: Andrew J. Mauer <ajmauer@gmail.com>
=> change order of java home resolution

pom.xml
=> Add tycho-p2-repository plugin

bundles/io.openliberty.tools.eclipse.ui/.settings/org.eclipse.jdt.core.prefs, pom.xml
=> Add explicit java target level to top-level pom.xml

bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml, bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF, ci/build.sh, ci/build3.sh, features/io.openliberty.tools.eclipse.feature/feature.xml, pom.xml, releng/io.openliberty.tools.update/category.xml, tests/META-INF/MANIFEST.MF, tests/pom.xml
=> Update versions prep for v0.1.1

bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml, bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF, features/io.openliberty.tools.eclipse.feature/feature.xml, pom.xml, releng/io.openliberty.tools.update/category.xml, tests/META-INF/MANIFEST.MF, tests/pom.xml
=> Prepare for next development release - 0.2.0

bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/mpls/LibertyMPLSConnection.java
=> Add debug port JVM prop

bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/terminal/ProjectTab.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/terminal/ProjectTabController.java
=> Set terminal working dir

bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java
=> Remove parm validation

releng/io.openliberty.tools.update/category.xml, releng/target-platform/target-platform.target
=> Use https for lsp4mp repo access

docs/installation/installation.md
=> Update site link

bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml, bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF, features/io.openliberty.tools.eclipse.feature/feature.xml, pom.xml, releng/io.openliberty.tools.update/category.xml, tests/META-INF/MANIFEST.MF, tests/pom.xml
=> Upgrade version to 0.4.0-SNAPSHOT

bundles/io.openliberty.tools.eclipse.lsp4e/.classpath, bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.lsp4e/build.properties, bundles/io.openliberty.tools.eclipse.lsp4e/plugin.xml, bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml, bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/liberty/languageserver/LibertyLSConnection.java, bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/liberty/languageserver/LibertyLSPlugin.java
Initial support for server.env and bootstrap.properties Liberty LS support
=> Liberty ls

bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.ui/plugin.xml, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/dashboard/DashboardEntryLabelProvider.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/dashboard/DashboardView.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigTabGroup.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigurationDelegateLauncher.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/MainTab.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/OpenGradleTestReportAction.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/OpenMavenITestReportAction.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/OpenMavenUTestReportAction.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/RunTestsAction.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartAction.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartInContainerAction.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StopAction.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/terminal/ProjectTab.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/utils/Utils.java, tests/META-INF/MANIFEST.MF, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java, tests/src/io/openliberty/tools/eclipse/test/it/utils/SWTPluginOperations.java
Run Configuration support prototype.
=> Add initial run configutation support.

bundles/io.openliberty.tools.eclipse.ui/plugin.xml, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotDashboardTest.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java, tests/src/io/openliberty/tools/eclipse/test/it/utils/SWTPluginOperations.java
=> Remove entry to open the dashboard from main UI menu

docs/installation/installation.md
=> Update doc for 0.4 release

releng/target-platform/target-platform.target
=> Update lsp4jakarta jar version

bundles/io.openliberty.tools.eclipse.ui/plugin.xml, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/LibertyResourceChangeListener.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/Project.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/handlers/ExplorerMenuHandler.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/dashboard/DashboardView.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/utils/Utils.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java, tests/src/io/openliberty/tools/eclipse/test/it/utils/LibertyPluginTestUtils.java, tests/src/io/openliberty/tools/eclipse/test/it/utils/SWTBotPluginOperations.java
=> Add liberty nature using the configure explorer menu

bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/CommandBuilder.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DebugModeHandler.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/LibertyResourceChangeListener.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/Project.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/WorkspaceProjectsModel.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/handlers/ExplorerMenuHandler.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/dashboard/DashboardEntryLabelProvider.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/dashboard/DashboardView.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/JRETab.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/StartTab.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/utils/Utils.java, tests/.classpath, tests/pom.xml, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMultiModMavenTest.java, tests/src/io/openliberty/tools/eclipse/test/it/utils/LibertyPluginTestUtils.java
* Treat multi-module aggregate module (for Maven) as Liberty nature project - Fixes #222 
* Add visible project field in Run Config - Fixes #186 
* Refactor - extracts finding of mvn/gradle launch command to separate class 
* Escalate JRE not JDK validation to error - Fixes #233 
* Adds application stop with wait
* Setup/teardown Mvn/Gradle preference at class level
=> Display proj in run config

bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF, features/io.openliberty.tools.eclipse.feature/feature.properties, features/io.openliberty.tools.eclipse.feature/feature.xml, releng/io.openliberty.tools.update/category.xml
=> Update vendor & feature name

bundles/io.openliberty.tools.eclipse.lsp4e/plugin.xml
See discussion in https://github.com/Microsoft/language-server-protocol/issues/674
=> Launch LS(s) as singletons

bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/terminal/ProjectTab.java
=> Run dev mode using the system shell.

bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/CommandBuilder.java
=> Add -x option for NIX for serviceability

bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigurationDelegateLauncher.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/StartTab.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/utils/Utils.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMultiModMavenTest.java
=> Prefer project name associated with run config

bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml, bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF, features/io.openliberty.tools.eclipse.feature/feature.xml, pom.xml, releng/io.openliberty.tools.update/category.xml, tests/META-INF/MANIFEST.MF, tests/pom.xml
=> Update version to 0.6.0

bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DebugModeHandler.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/LibertyNature.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/Project.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/WorkspaceProjectsModel.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/handlers/ExplorerMenuHandler.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMultiModMavenTest.java, tests/src/io/openliberty/tools/eclipse/test/it/utils/SWTBotPluginOperations.java
=> Allow top level project to run in debug mode

bundles/io.openliberty.tools.eclipse.lsp4e/.classpath, bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.lsp4e/build.properties, bundles/io.openliberty.tools.eclipse.lsp4e/plugin.xml, bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml, bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/jakarta/languageserver/JakartaLSConnection.java, bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/liberty/languageserver/LibertyLSConnection.java, bundles/io.openliberty.tools.eclipse.ui/plugin.xml, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DebugModeHandler.java, releng/io.openliberty.tools.update/category.xml, releng/target-platform/target-platform.target
Fixes #291 , and at the same time moves up to the latest snapshots for LCLS/LSP4Jakarta
=> Simplify debug

bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml
=> Remove shade plugin from lsp4e bundle build

bundles/io.openliberty.tools.eclipse.lsp4e/plugin.xml
=> Adjust LS names in LS Preferences panel

features/io.openliberty.tools.eclipse.feature/feature.properties, features/io.openliberty.tools.eclipse.feature/license.html
=> Upgrade NOTICES link

docs/installation/installation.md
=> update install doc for 0.7.0

docs/installation/installation.md
=> Update release link

pom.xml
The newer tycho version fixes https://github.com/eclipse-tycho/tycho/issues/425 which is seen in our jenkins builds
=> Update Tycho version

.github/workflows/run-regression-tests.yml, tests/pom.xml, tests/resources/applications/maven/liberty-maven-test-app/pom.xml, tests/resources/applications/maven/non-dflt-server-xml-path/mvnw, tests/resources/applications/maven/non-dflt-server-xml-path/mvnw.cmd, tests/resources/applications/maven/non-dflt-server-xml-path/pom.xml, tests/resources/applications/maven/non-dflt-server-xml-path/src/main/java/test/maven/liberty/web/app/HelloServlet.java, tests/resources/applications/maven/non-dflt-server-xml-path/src/main/liberty/config/my.xml, tests/resources/applications/maven/non-dflt-server-xml-path/src/main/webapp/WEB-INF/web.xml, tests/resources/applications/maven/non-dflt-server-xml-path/src/main/webapp/index.html, tests/resources/applications/maven/non-dflt-server-xml-path/src/test/java/test/maven/liberty/web/app/ApplicationTest.java, tests/resources/applications/maven/non-dflt-server-xml-path/src/test/java/test/maven/liberty/web/app/it/EndpointIT.java, tests/resources/ci/scripts/exec.sh, tests/resources/ci/scripts/setup.sh, tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java
=> Fix for issue 232 - reenable test

.github/workflows/run-regression-tests.yml, bundles/io.openliberty.tools.eclipse.lsp4e/.classpath, bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.lsp4e/build.properties, bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml, bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/mpls/LibertyMPLSClientImpl.java, bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/mpls/LibertyMPLSConnection.java, bundles/io.openliberty.tools.eclipse.product/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF, features/io.openliberty.tools.eclipse.feature/feature.xml, pom.xml, releng/io.openliberty.tools.update/category.xml, releng/target-platform-1Q2023/target-platform-1Q2023.target, releng/target-platform-3Q2022/target-platform-3Q2022.target, releng/target-platform-4Q2022/target-platform-4Q2022.target, tests/META-INF/MANIFEST.MF, tests/pom.xml
=> Enable runtime for 1Q23

docs/user-guide.md
=> Gradle import instructions

docs/user-guide.md
=> install versions

docs/installation.md
=> Fix install doc link to user guide

bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF, bundles/io.openliberty.tools.eclipse.ui/plugin.xml, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/CommandBuilder.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/debug/DebugModeHandler.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/debug/LibertySourceLookupDirector.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/debug/LibertySourcePathComputer.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/dashboard/DashboardView.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigTabGroup.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigurationDelegateLauncher.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigurationHelper.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartAction.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartInContainerAction.java, tests/META-INF/MANIFEST.MF, tests/resources/applications/gradle/liberty-gradle-test-app/build.gradle, tests/resources/applications/maven/liberty-maven-test-app/pom.xml, tests/resources/applications/maven/maven-multi-module/typeJ/war2/src/main/webapp/META-INF/MANIFEST.MF, tests/resources/applications/maven/shared-lib/pom.xml, tests/resources/applications/maven/shared-lib/src/main/java/io/openliberty/guides/multimodules/lib/Converter.java, tests/src/main/java/io/openliberty/tools/eclipse/test/it/AbstractLibertyPluginSWTBotTest.java, tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java, tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java, tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMultiModMavenTest.java, tests/src/main/java/io/openliberty/tools/eclipse/test/it/utils/SWTBotPluginOperations.java, tests/src/main/java/io/openliberty/tools/eclipse/test/ut/LibertyPluginUnitTest.java
Would supersede #437 . Same content.
=> Use Liberty Tools Debug Config

bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml, releng/io.openliberty.tools.update/category.xml, releng/target-platform-3Q2024/target-platform-3Q2024.target
- Updates LSP4MP to 0.13.2
- Updates LSP4Jakarta to 0.2.2
- Updates JDTLS to 1.42.0
- Updates listing in target platform for 3Q2024 including:
- SWTBot v4.2.1
- CDT v11.6
=> Update dependencies for 24.0.12 release

CHANGELOG.md, docs/installation.md, docs/user-guide.md
Doc and Changelog updates for 24.0.12
=> Final 2412

bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigurationDelegateLauncher.java, bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/StartTab.java, tests/META-INF/MANIFEST.MF, tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java, tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java, tests/src/main/java/io/openliberty/tools/eclipse/test/it/utils/LibertyPluginTestUtils.java, tests/src/main/java/io/openliberty/tools/eclipse/test/it/utils/SWTBotPluginOperations.java
Reverts OpenLiberty/liberty-tools-eclipse#554
=> Revert "Added mvn clean option under liberty in run configurations "

NOTICES
Updated NOTICES file based on latest Mend scan dependency list
=> Update NOTICES for new dependencies
