- liberty/plugin.xml
- liberty/src/liberty/tools/ui/DashboardView.java
When selecting the option to start the Liberty server in dev mode with parms, the request should not be processed if the user closes the argument dialog window or presses cancel.
> Process start with parm request on OK only

- liberty/src/liberty/tools/DevModeOperations.java
This changes will allow to:
- Create a terminal that based on your local shell.
- Not need to hard code a maven/gradle path if you have set/exported (i.e. .bashrc, .zshrc, etc.) your MAVEN/GRADLE_HOME paths or you have the mvn/gradle executable in your path.
- Prevent the behavior that restarts the command when hitting enter on the terminal after it is closed.
- etc.
> Terminal related updates

- .project
- bundles/liberty/META-INF/MANIFEST.MF
- bundles/liberty/plugin.xml
- bundles/liberty/src/liberty/tools/DevModeOperations.java
- bundles/liberty/src/liberty/tools/ui/DashboardView.java
- bundles/liberty/src/liberty/tools/ui/terminal/LocalDevModeLauncherDelegate.java
- bundles/liberty/src/liberty/tools/ui/terminal/TerminalTabListenerImpl.java
This is a prototype that allows Liberty devMode commands run on a terminal.
Note that this implementation requires the use/reference of an Eclipse API that has been marked as internal and experimental. An Eclipse forum query about the API use is pending an answer.
> Prototype updates to support running all required devMode actions on a terminal

- bundles/liberty/src/liberty/tools/DevModeOperations.java
- bundles/liberty/src/liberty/tools/ui/terminal/ProjectTab.java
- bundles/liberty/src/liberty/tools/ui/terminal/ProjectTabController.java
This PR handles the case where the terminal tab running the devmode on an specific project is marked as closed (deactivated) unexpectedly due to an error (i.e running mvn command: cannot find mvn installation, etc) or due to an external user action (i.e. user manually terminated dev mode, etc).
> Handle closed tabs due to errors or external actions.

- ci/Dockerfile
- ci/build.sh
- ci/build3.sh
- pom.xml
ci build occurs in 3 phases for now:
* phase 1: run build.sh to build image and copy out the install repo artifacts.
* phase 2: using the artifacts, sign the 3 jar files
1. features/io.openliberty.tools.eclipse.feature_0.1.0.jar
2. plugins/io.openliberty.tools.eclipse.lsp4e_0.1.0.jar
3. plugins/io.openliberty.tools.eclipse.ui_0.1.0.jar
overlay the original versions of those jars with the newly signed jars
* phase 3: run build3.sh - will copy the 3 signed jars into the container, run the mvn -pl command to update the artifacts.xml.xz file with the signing info and then copies that xml file out of the container and into the local repository file structure
> Fix repo build - sign and update artifacts for installation

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/terminal/LocalDevModeLauncherDelegate.java
This PR solves the error that occurs when restarting the Eclipse IDE after it was shutdown while terminal views were still running applications in dev mode. The following error is seen on the terminal view after restart:
```
java.lang.NullPointerException
at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at io.openliberty.tools.eclipse.ui.terminal.ProjectTabController.getProjectConnector(ProjectTabController.java:165)
at io.openliberty.tools.eclipse.ui.terminal.LocalDevModeLauncherDelegate.createTerminalConnector(LocalDevModeLauncherDelegate.java:55)
at org.eclipse.tm.terminal.view.ui.services.TerminalService.createTerminalConnector(TerminalService.java:246)
at org.eclipse.tm.terminal.view.ui.services.TerminalService.executeServiceOperation(TerminalService …
```
> Fix NPE on terminal after Eclipse restart

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/Dashboard.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/Project.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/DashboardEntryLabelProvider.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/DashboardView.java
- releng/target-platform/target-platform.target
- tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java
- tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java
- tests/src/io/openliberty/tools/eclipse/test/it/utils/SWTPluginOperations.java
This a post-early-release PR that does the following:
- Updates the test report tab titles to contain the project name. This aligns with the other Liberty dev tools.
- Limits dashboard project selection to only one project at a time.
- Sorts the projects in the dashboard in two groups (maven/gradle) and alphabetically orders the projects within those two groups. The projects are separated visually using icons provided by m2e and buildship plugins. One TODO from this is to investigate if approval of some sort is needed to use these images (#136 ).
Fixes #49
> Organize projects on Dashboard and test reporting updates.

- bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF
- bundles/io.openliberty.tools.eclipse.ui/plugin.xml
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/dashboard/DashboardView.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigurationDelegateLauncher.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/MainTab.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/OpenGradleTestReportAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/OpenMavenITestReportAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/OpenMavenUTestReportAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/RunTestsAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartConfigurationDialogAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartInContainerAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StopAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/utils/Dialog.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/utils/Utils.java
- releng/target-platform/target-platform.target
- tests/META-INF/MANIFEST.MF
- tests/pom.xml
- tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotDashboardTest.java
- tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java
- tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java
- tests/src/io/openliberty/tools/eclipse/test/it/utils/SWTBotPluginOperations.java
- tests/src/io/openliberty/tools/eclipse/test/it/utils/SWTBotTestCondition.java
- tests/src/io/openliberty/tools/eclipse/test/ut/LibertyPluginUnitTest.java
This PR among others does the following:
- Adds the start… selection to the Run As configuration shortcuts.
- Further links and standardizes all action commands in the dashboard and the Run As shortcuts.
- Introduces a new checkbox in the run configurations dialog Main tab. This allows the user to select whether or not to run dev mode locally or in a container. It replaces the need for a new “Start in container…“ option.
- Adds configuration filtering based on whether the current action is meant to run in a container or locally.
- Re-defines “start…” in the sense that it now opes the run configurations dialog for user customization.
- Updates the error/warning dialog title from "Liberty Dev Mode" to "Liberty Tools"
- Adds unit tests.
> Run configuration and core rework/updates

- bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/jakarta/languageserver/JakartaLSConnection.java
- bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/liberty/languageserver/LibertyLSConnection.java
- bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/mpls/LibertyMPLSConnection.java
The java.home property will be set with the JRE used to launch Eclipse
> Use java.home for launching LS processes 

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/MainTab.java
This PR properly disposes of the image when the configuration dialog is closed.
It fixes this error:
java.lang.Error: SWT Resource was not properly disposed
at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
at org.eclipse.swt.graphics.Image.<init>(Image.java:684)
at io.openliberty.tools.eclipse.utils.Utils.getLibertyImage(Utils.java:57)
at io.openliberty.tools.eclipse.ui.launch.MainTab.getImage(MainTab.java:192)
at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.refresh(LaunchConfigurationTabGroupViewer.java:539)
at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.updateButtons(LaunchConfigurationsDialog.java:1630)
at …
> Dispose of image tab properly.

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/OpenGradleTestReportAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/OpenMavenITestReportAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/OpenMavenUTestReportAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/RunTestsAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartConfigurationDialogAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StartInContainerAction.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/shortcuts/StopAction.java
- releng/io.openliberty.tools.update/category.xml
This PR allows the tracing facility to be enabled when using Eclipse IDE for Java Developers.
> Add trace dependency for Java Devs Eclipse IDE

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/terminal/ProjectTab.java
fixes #264 
This PR fixes the error below that appears when a terminal tab running a project is closed.
java.lang.Error: SWT Resource was not properly disposed
at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
at org.eclipse.swt.graphics.Image.<init>(Image.java:684)
at io.openliberty.tools.eclipse.utils.Utils.getImage(Utils.java:68)
at io.openliberty.tools.eclipse.ui.terminal.ProjectTab.lambda$0(ProjectTab.java:176)
at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4318)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3941) …
> Dispose of terminal tab image

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/StartTab.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/preferences/LibertyToolsPreferencePage.java
Liberty configuration dialog:
Fixes https://github.com/OpenLiberty/liberty-tools-eclipse/issues/107 (perhaps not as originally written but in the sense it's the final UI adjustment)
> Organize Liberty start tab in configuration dialog

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/LibertyNature.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/handlers/ExplorerMenuHandler.java
Currently a "Configure -> Enable Liberty" doesn't auto-refresh the dashboard.  With this change we refresh the DB on Configure AND also if you right-click the proj. and do "Properties -> Project Natures -> Add -> ...Liberty".
Because of this there was no need to do another workspace model build within configure so I removed it.
> Add refresh on add of Liberty Nature

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DebugModeHandler.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/dashboard/DashboardView.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/terminal/ProjectTabController.java
This PR does the following:
- When the debugger attaches successfully, the perspective changed to show the debug perspective if it is not already shown.
- Fixes port issues when project specifies a port through server.env.
- Increases the debugger attach wait time to account for longer Gradle wait times.
> Open debug perspective after successful debugger connection

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/StartTab.java
- tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java
- tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMultiModMavenTest.java
Fixes two problems when no project is selected:
1. Run/Debug config isn't associated with any project.  Since there's no way to set the project post-creation, this config is now "corrupted" and a new one is needed.  Add validation error message explaining this.
2. Validation blows up with NPE if no project is selected at the time a Run/Debug config is selected.  Add null check
> Fix problems when no project is selected

- features/io.openliberty.tools.eclipse.feature/feature.properties
- features/io.openliberty.tools.eclipse.feature/license.html
Fixes https://github.com/OpenLiberty/liberty-tools-eclipse/issues/219
As discussed internally, we're going to "lead" with a simple copy/paste of EPL v2.0.
At the end, we're going to link to the particular NOTICES from our various dependencies.  
At the moment, the only dependency with anything interesting captured is the one LCLS dependency.   So I simply ended the license text with a reference to the LCLS NOTICES file in the LCLS source repo.
It ends up looking like this, in the Eclipse UI install wizard panel (scrolling down to the bottom):
and it looks like this in the `license.html` included with the feature install directory:
> Add link to LCLS NOTICES at end of EPL v2.0 license

- tests/src/io/openliberty/tools/eclipse/test/it/utils/SWTBotPluginOperations.java
Explicitly set the focus when selecting "Liberty" in "Preferences".   This is needed when running the tests in Jenkins.
> Add setFocus

- NOTICES
- features/io.openliberty.tools.eclipse.feature/feature.properties
- features/io.openliberty.tools.eclipse.feature/license.html
Fixes #370 .
Noted in https://github.com/OpenLiberty/liberty-tools-eclipse/issues/192#issuecomment-1561931189 that the link here assumes we create a special tag in addition to our release tag including the build timestamp.   (Or we can later go update this link again).
> Add 23.0.1 NOTICES file

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DebugModeHandler.java
Fixes #372 
This might be all that's needed. 
I'm not familiar enough with the underlying APIs, e.g. **org.eclipse.debug.core.ILaunchConfigurationWorkingCopy** to really know what I'm talking about... BUT.. it seems like I could kind of rationalize it by saying the working copy is for editing but use the original launch config for actually calling launch().
Might try to read a bit more.
> Launch debug from original LaunchConfiguration rather than copy in order to persist source lookup modifications

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/StartTab.java
Adds:
*  Alt+c for "Run in Container"
* Alt+p for "Start parameters"
Note these are case-insensitive
> Add keyboard shortcuts for StartTab fields

- .github/workflows/run-regression-tests.yml
- bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF
- bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml
- bundles/io.openliberty.tools.eclipse.product/META-INF/MANIFEST.MF
- bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF
- ci/jenkins/run-tests
- features/io.openliberty.tools.eclipse.feature/feature.xml
- pom.xml
- releng/io.openliberty.tools.update/category.xml
- releng/target-platform-2Q2023/target-platform-2Q2023.target
- tests/META-INF/MANIFEST.MF
- tests/pom.xml
- tests/resources/applications/gradle/liberty-gradle-test-app/build.gradle
- tests/resources/applications/gradle/liberty-gradle-test-wrapper-app/build.gradle
- tests/resources/ci/scripts/exec.sh
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotDashboardTest.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMultiModMavenTest.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/utils/SWTBotPluginOperations.java
- Update LCLS to version 2.0.1
- Bump version to 23.0.9
- Create 2Q2023 target platform file
- Update peripheral scripts to use 2Q2023 target platform
> 2023-06 IDE support

- bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/jakarta/languageserver/JakartaLSConnection.java
- bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/liberty/languageserver/LibertyLSConnection.java
- bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/lsclient/DebugUtil.java
- bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/mpls/LibertyMPLSConnection.java
As noted on the [wiki](https://github.com/OpenLiberty/liberty-tools-eclipse/wiki/Debug-Options#suspend)
By default the JVM will launch but not be suspended, when the debug port is set.
To start the JVM in a suspended state while the debugger is attached, use, e.g:
> -Dio.openliberty.tools.eclipse.mpls.LibertyMPLSConnection.debugSuspend=y
(use the corresponding property for each LS based on the classnames above)
> Rework debugger config to default to suspend=n

- bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/mpls/LibertyMPLSClientImpl.java
Fixes #377 
Though I'm not aware of it being spec'd or somehow enforced, there is a naming convention buried within the diagnostic fields... the LSP4Jakarta ones all start with "jakarta" and the LSP4MP ones "microprofile".
It comes from the source code like:
**org.eclipse.lsp4jakarta.jdt.internal.servlet.Constants.DIAGNOSTIC_SOURCE**
> Ignore MP code action request for non-MP diagnostics

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigTabGroup.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/utils/SWTBotPluginOperations.java
Adds the Common tab to the Run Configurations.  Added a test to launch the tab, and validated that the test failed when the Common tab is not added.
> Add Common tab with test

- bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF
- bundles/io.openliberty.tools.eclipse.lsp4e/plugin.xml
- bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml
- bundles/io.openliberty.tools.eclipse.lsp4e/src/io/openliberty/tools/eclipse/liberty/languageserver/LibertyLSClientImpl.java
Add a resource changed listener to send "didChangedWatchedFiles" events to the Liberty Config LS on any changes to liberty-plugin-config.xml and all *.properties and *.env files.
Resolves issue #461 
Addresses required changes in LCLS PR https://github.com/OpenLiberty/liberty-language-server/pull/212
> Add LCLS change listener

- bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml
> Update to LCLS 2.2

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/CommandBuilder.java
- tests/resources/execs/mvn
- tests/resources/execs/mvn.cmd
- tests/src/main/java/io/openliberty/tools/eclipse/test/ut/CommandBuilderTest.java
It seems that the "blank" preference will sometimes allow /bin/mvn to resolve.  OTOH, this would typically resolve as part of the PATH, so removing it might be cleaner.
Still it's not exactly zero side effects, so let's review.
> Fixes #527

- .github/workflows/run-regression-tests.yml
- bundles/io.openliberty.tools.eclipse.lsp4e/META-INF/MANIFEST.MF
- bundles/io.openliberty.tools.eclipse.lsp4e/pom.xml
- bundles/io.openliberty.tools.eclipse.product/META-INF/MANIFEST.MF
- bundles/io.openliberty.tools.eclipse.ui/META-INF/MANIFEST.MF
- ci/jenkins/run-tests
- features/io.openliberty.tools.eclipse.feature/feature.xml
- pom.xml
- releng/io.openliberty.tools.update/category.xml
- releng/target-platform-4Q2024/target-platform-4Q2024.target
- tests/META-INF/MANIFEST.MF
- tests/pom.xml
- Update version to 25.0.3
- Creates new target platform for Eclipse 24.0.12 and updates the default 
No changes needed to dependencies (LCLS, LSP4MP, LSP4Jakarta, etc) - already at current
> 2503 release

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/CommandBuilder.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/LaunchConfigurationDelegateLauncher.java
- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/ui/launch/StartTab.java
- tests/META-INF/MANIFEST.MF
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotGradleTest.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/utils/LibertyPluginTestUtils.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/utils/SWTBotPluginOperations.java
Fixes #239 
changes includes : 
Adding a new check box to enable project clean option under liberty in run configurations .
Test cases for the new Run project clean check box added for both Gradle and maven projects
> Added mvn clean option under liberty in run configurations 

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotDebuggerTest.java
- tests/src/main/java/io/openliberty/tools/eclipse/test/it/utils/LibertyPluginTestUtils.java
part of #562 
Test cases for enhanced debug mode.
- Validate xml file with app monitoring configuration is present in 'configDropins/overrides' directory when dev mode starts in debug mode.
- Validate xml file with app monitoring configuration is removed from 'configDropins/overrides' directory when debugger disconnects from the dev mode.
- Validate xml file with app monitoring configuration is removed from 'configDropins/overrides' directory when dev mode stops
> Added Test case for enhanced debug mode

- bundles/io.openliberty.tools.eclipse.ui/src/io/openliberty/tools/eclipse/DevModeOperations.java
Removing the next line character after 'r' command, because it is running the unit tests automatically.
> SVT issue - Removing the next line character after 'r' command.
